/*----------------------------------------------------------------------------------*/
/* Product:            Visual Data Mining and Machine Learning                      */
/* Release Version:    V2023.03                                                     */
/* Component Version:  V2023.03                                                     */
/* CAS Version:        V.04.00M0P03132023                                           */
/* SAS Version:        V.04.00M0P031323                                             */
/* Site Number:        70180938                                                     */
/* Host:               sas-cas-server-default-client                                */
/* Encoding:           utf-8                                                        */
/* Java Encoding:      UTF8                                                         */
/* Locale:             en_US                                                        */
/* Project GUID:       704f35db-de39-4dc5-a559-b56d05b5f649                         */
/* Node GUID:          99a585cf-3541-464c-82ad-d4db34d0af8d                         */
/* Node Id:            93GQLBVUVAYYGWZUXHWT8P1FX                                    */
/* Algorithm:          Logistic Regression                                          */
/* Generated by:       emlynwang                                                    */
/* Date:               13APR2023:07:32:52                                           */
/*----------------------------------------------------------------------------------*/
package MS_99a585cf3541464c82add4db34d0af8d_13APR2023073252186 / overwrite=yes;
   dcl package score _ZT5K8HFT9737OKKI23QHL6U1();
   dcl double "AVG_of_AMP01";
   dcl double "AVG_of_AMP1";
   dcl double "AVG_of_AMP10";
   dcl double "AVG_of_AMP11";
   dcl double "AVG_of_AMP12";
   dcl double "AVG_of_AMP13";
   dcl double "AVG_of_AMP14";
   dcl double "AVG_of_AMP15";
   dcl double "AVG_of_AMP16";
   dcl double "AVG_of_AMP2";
   dcl double "AVG_of_AMP3";
   dcl double "AVG_of_AMP4";
   dcl double "AVG_of_AMP5";
   dcl double "AVG_of_AMP6";
   dcl double "AVG_of_AMP7";
   dcl double "AVG_of_AMP8";
   dcl double "AVG_of_AMP9";
   dcl double "AVG_of_BLOWER01";
   dcl double "AVG_of_BLOWER02";
   dcl double "AVG_of_DEWPOINT01";
   dcl double "AVG_of_DPT01";
   dcl double "AVG_of_DPT02";
   dcl double "AVG_of_FEEDAMP";
   dcl double "AVG_of_FEEDHZ";
   dcl double "AVG_of_FLOW";
   dcl double "AVG_of_HZ01";
   dcl double "AVG_of_MILLAMP";
   dcl double "AVG_of_MILLHZ";
   dcl double "AVG_of_O2FT_MAIN";
   dcl double "AVG_of_PRESSURE01";
   dcl double "AVG_of_SEPAMP";
   dcl double "AVG_of_SEPHZ";
   dcl double "AVG_of_SPEED";
   dcl double "AVG_of_TEMP3";
   dcl double "AVG_of_TEMP4";
   dcl double "AVG_of_TEMP5";
   dcl double "AVG_of_TEMP6";
   dcl double "VALUE";
   dcl varchar(4) "INSP_ITEM";
   dcl double "LSL";
   dcl double "USL";
   dcl double "_CLUSTER_ID_";
   dcl double "_DISTANCE_";
   dcl double "_STANDARDIZED_DISTANCE_";
   dcl double "P_DEFMIS_H" having label n'Predicted: DEF=MIS_H';
   dcl double "P_DEFOK" having label n'Predicted: DEF=OK';
   dcl double EM_EVENTPROBABILITY;
   dcl nchar(5) EM_CLASSIFICATION;
   dcl double EM_PROBABILITY;
   dcl nchar(5) "I_DEF" having label n'Into: DEF';
   varlist allvars [_all_];
 
    
   method init();
      _ZT5K8HFT9737OKKI23QHL6U1.setvars(allvars);
      _ZT5K8HFT9737OKKI23QHL6U1.setkey(n'C912D4A7E4CCEE84DABC5B842DF55D2D2BDFDDD4');
   end;
    
   method _93GQLBVUVAYYGWZUXHWT8P1FX();
      dcl double _P_;
      dcl double MACLOGBIG;
      dcl double _J_;
      dcl double _I_;
      dcl double _TEMP_;
      dcl double _LINP_;
      dcl double _BADVAL_;
      dcl nchar(5) _LEVELS_95517271_[2];
      dcl double _BETA_95517271_0_[2];
      dcl double _XROW_95517271_0_[2];
       
      _LEVELS_95517271_:=('OK', 'MIS_H');
      _BETA_95517271_0_:=(5.41689105770283, -1.3959292806597);
      _BADVAL_ = 0.0;
      _LINP_ = 0.0;
      _TEMP_ = 0.0;
      _I_ = 0.0;
      _J_ = 0.0;
      MACLOGBIG = 7.0978271289338392E+02;
      if MISSING(AVG_OF_BLOWER02) then do ;
      _BADVAL_ = 1.0;
      goto SKIP_95517271_0;
      end;
      do _I_ = 1.0 to 2.0;
      _XROW_95517271_0_[_I_] = 0.0;
      end;
      _XROW_95517271_0_[1.0] = 1.0;
      _XROW_95517271_0_[2.0] = AVG_OF_BLOWER02;
      do _I_ = 1.0 to 2.0;
      _LINP_ + _XROW_95517271_0_[_I_] * _BETA_95517271_0_[_I_];
      end;
      SKIP_95517271_0: if (_BADVAL_ = 0.0) & ^MISSING(_LINP_) then do ;
      if (_LINP_ > 0.0) then do ;
      P_DEFOK = 1.0 / (1.0 + EXP(-_LINP_));
      end;
      else do ;
      P_DEFOK = EXP(_LINP_) / (1.0 + EXP(_LINP_));
      end;
      P_DEFMIS_H = 1.0 - P_DEFOK;
      if P_DEFOK >= 0.5 then do ;
      I_DEF = _LEVELS_95517271_[1.0];
      end;
      else do ;
      I_DEF = _LEVELS_95517271_[2.0];
      end;
      end;
      else do ;
      _LINP_ = .;
      P_DEFOK = .;
      P_DEFMIS_H = .;
      I_DEF = ' ';
      end;
      if "P_DEFMIS_H" = . then "P_DEFMIS_H" = 0.0360576923;
      if "P_DEFOK" = . then "P_DEFOK" = 0.9639423077;
      if MISSING("I_DEF") then do ;
      _P_ = 0.0;
      if "P_DEFOK" > _P_ then do ;
      _P_ = "P_DEFOK";
      "I_DEF" = 'OK';
      end;
      if "P_DEFMIS_H" > _P_ then do ;
      _P_ = "P_DEFMIS_H";
      "I_DEF" = 'MIS_H';
      end;
      end;
    
   end;
    
   method post_93GQLBVUVAYYGWZUXHWT8P1FX();
      dcl double _P_;
       
      EM_EVENTPROBABILITY = "P_DEFOK";
      EM_CLASSIFICATION = "I_DEF";
      EM_PROBABILITY = MAX("P_DEFOK", "P_DEFMIS_H");
    
   end;
    
 
   method score(
      double "AVG_of_AMP01",
      double "AVG_of_AMP1",
      double "AVG_of_AMP10",
      double "AVG_of_AMP11",
      double "AVG_of_AMP12",
      double "AVG_of_AMP13",
      double "AVG_of_AMP14",
      double "AVG_of_AMP15",
      double "AVG_of_AMP16",
      double "AVG_of_AMP2",
      double "AVG_of_AMP3",
      double "AVG_of_AMP4",
      double "AVG_of_AMP5",
      double "AVG_of_AMP6",
      double "AVG_of_AMP7",
      double "AVG_of_AMP8",
      double "AVG_of_AMP9",
      double "AVG_of_BLOWER01",
      double "AVG_of_BLOWER02",
      double "AVG_of_DEWPOINT01",
      double "AVG_of_DPT01",
      double "AVG_of_DPT02",
      double "AVG_of_FEEDAMP",
      double "AVG_of_FEEDHZ",
      double "AVG_of_FLOW",
      double "AVG_of_HZ01",
      double "AVG_of_MILLAMP",
      double "AVG_of_MILLHZ",
      double "AVG_of_O2FT_MAIN",
      double "AVG_of_PRESSURE01",
      double "AVG_of_SEPAMP",
      double "AVG_of_SEPHZ",
      double "AVG_of_SPEED",
      double "AVG_of_TEMP3",
      double "AVG_of_TEMP4",
      double "AVG_of_TEMP5",
      double "AVG_of_TEMP6",
      varchar(4) "INSP_ITEM",
      double "LSL",
      double "USL",
      double "VALUE",
      IN_OUT char(5) "EM_CLASSIFICATION",
      IN_OUT double "EM_EVENTPROBABILITY",
      IN_OUT double "EM_PROBABILITY",
      IN_OUT char(5) "I_DEF",
      IN_OUT double "P_DEFMIS_H",
      IN_OUT double "P_DEFOK",
      IN_OUT double "_CLUSTER_ID_",
      IN_OUT double "_DISTANCE_",
      IN_OUT double "_STANDARDIZED_DISTANCE_"
   );
      this."AVG_of_AMP01"= "AVG_of_AMP01";
      this."AVG_of_AMP1"= "AVG_of_AMP1";
      this."AVG_of_AMP10"= "AVG_of_AMP10";
      this."AVG_of_AMP11"= "AVG_of_AMP11";
      this."AVG_of_AMP12"= "AVG_of_AMP12";
      this."AVG_of_AMP13"= "AVG_of_AMP13";
      this."AVG_of_AMP14"= "AVG_of_AMP14";
      this."AVG_of_AMP15"= "AVG_of_AMP15";
      this."AVG_of_AMP16"= "AVG_of_AMP16";
      this."AVG_of_AMP2"= "AVG_of_AMP2";
      this."AVG_of_AMP3"= "AVG_of_AMP3";
      this."AVG_of_AMP4"= "AVG_of_AMP4";
      this."AVG_of_AMP5"= "AVG_of_AMP5";
      this."AVG_of_AMP6"= "AVG_of_AMP6";
      this."AVG_of_AMP7"= "AVG_of_AMP7";
      this."AVG_of_AMP8"= "AVG_of_AMP8";
      this."AVG_of_AMP9"= "AVG_of_AMP9";
      this."AVG_of_BLOWER01"= "AVG_of_BLOWER01";
      this."AVG_of_BLOWER02"= "AVG_of_BLOWER02";
      this."AVG_of_DEWPOINT01"= "AVG_of_DEWPOINT01";
      this."AVG_of_DPT01"= "AVG_of_DPT01";
      this."AVG_of_DPT02"= "AVG_of_DPT02";
      this."AVG_of_FEEDAMP"= "AVG_of_FEEDAMP";
      this."AVG_of_FEEDHZ"= "AVG_of_FEEDHZ";
      this."AVG_of_FLOW"= "AVG_of_FLOW";
      this."AVG_of_HZ01"= "AVG_of_HZ01";
      this."AVG_of_MILLAMP"= "AVG_of_MILLAMP";
      this."AVG_of_MILLHZ"= "AVG_of_MILLHZ";
      this."AVG_of_O2FT_MAIN"= "AVG_of_O2FT_MAIN";
      this."AVG_of_PRESSURE01"= "AVG_of_PRESSURE01";
      this."AVG_of_SEPAMP"= "AVG_of_SEPAMP";
      this."AVG_of_SEPHZ"= "AVG_of_SEPHZ";
      this."AVG_of_SPEED"= "AVG_of_SPEED";
      this."AVG_of_TEMP3"= "AVG_of_TEMP3";
      this."AVG_of_TEMP4"= "AVG_of_TEMP4";
      this."AVG_of_TEMP5"= "AVG_of_TEMP5";
      this."AVG_of_TEMP6"= "AVG_of_TEMP6";
      this."INSP_ITEM"= "INSP_ITEM";
      this."LSL"= "LSL";
      this."USL"= "USL";
      this."VALUE"= "VALUE";
 
      _ZT5K8HFT9737OKKI23QHL6U1.scoreRecord();
      _93GQLBVUVAYYGWZUXHWT8P1FX();
      post_93GQLBVUVAYYGWZUXHWT8P1FX();
 
      "EM_CLASSIFICATION"= this."EM_CLASSIFICATION";
      "EM_EVENTPROBABILITY"= this."EM_EVENTPROBABILITY";
      "EM_PROBABILITY"= this."EM_PROBABILITY";
      "I_DEF"= this."I_DEF";
      "P_DEFMIS_H"= this."P_DEFMIS_H";
      "P_DEFOK"= this."P_DEFOK";
      "_CLUSTER_ID_"= this."_CLUSTER_ID_";
      "_DISTANCE_"= this."_DISTANCE_";
      "_STANDARDIZED_DISTANCE_"= this."_STANDARDIZED_DISTANCE_";
   end;
 
 
   method predictedscore(
      double "AVG_of_AMP01",
      double "AVG_of_AMP1",
      double "AVG_of_AMP10",
      double "AVG_of_AMP11",
      double "AVG_of_AMP12",
      double "AVG_of_AMP13",
      double "AVG_of_AMP14",
      double "AVG_of_AMP15",
      double "AVG_of_AMP16",
      double "AVG_of_AMP2",
      double "AVG_of_AMP3",
      double "AVG_of_AMP4",
      double "AVG_of_AMP5",
      double "AVG_of_AMP6",
      double "AVG_of_AMP7",
      double "AVG_of_AMP8",
      double "AVG_of_AMP9",
      double "AVG_of_BLOWER01",
      double "AVG_of_BLOWER02",
      double "AVG_of_DEWPOINT01",
      double "AVG_of_DPT01",
      double "AVG_of_DPT02",
      double "AVG_of_FEEDAMP",
      double "AVG_of_FEEDHZ",
      double "AVG_of_FLOW",
      double "AVG_of_HZ01",
      double "AVG_of_MILLAMP",
      double "AVG_of_MILLHZ",
      double "AVG_of_O2FT_MAIN",
      double "AVG_of_PRESSURE01",
      double "AVG_of_SEPAMP",
      double "AVG_of_SEPHZ",
      double "AVG_of_SPEED",
      double "AVG_of_TEMP3",
      double "AVG_of_TEMP4",
      double "AVG_of_TEMP5",
      double "AVG_of_TEMP6",
      varchar(4) "INSP_ITEM",
      double "LSL",
      double "USL",
      double "VALUE",
      IN_OUT char(5) "EM_CLASSIFICATION",
      IN_OUT double "EM_EVENTPROBABILITY",
      IN_OUT double "EM_PROBABILITY",
      IN_OUT char(5) "I_DEF",
      IN_OUT double "P_DEFMIS_H",
      IN_OUT double "P_DEFOK"
   );
      this."AVG_of_AMP01"= "AVG_of_AMP01";
      this."AVG_of_AMP1"= "AVG_of_AMP1";
      this."AVG_of_AMP10"= "AVG_of_AMP10";
      this."AVG_of_AMP11"= "AVG_of_AMP11";
      this."AVG_of_AMP12"= "AVG_of_AMP12";
      this."AVG_of_AMP13"= "AVG_of_AMP13";
      this."AVG_of_AMP14"= "AVG_of_AMP14";
      this."AVG_of_AMP15"= "AVG_of_AMP15";
      this."AVG_of_AMP16"= "AVG_of_AMP16";
      this."AVG_of_AMP2"= "AVG_of_AMP2";
      this."AVG_of_AMP3"= "AVG_of_AMP3";
      this."AVG_of_AMP4"= "AVG_of_AMP4";
      this."AVG_of_AMP5"= "AVG_of_AMP5";
      this."AVG_of_AMP6"= "AVG_of_AMP6";
      this."AVG_of_AMP7"= "AVG_of_AMP7";
      this."AVG_of_AMP8"= "AVG_of_AMP8";
      this."AVG_of_AMP9"= "AVG_of_AMP9";
      this."AVG_of_BLOWER01"= "AVG_of_BLOWER01";
      this."AVG_of_BLOWER02"= "AVG_of_BLOWER02";
      this."AVG_of_DEWPOINT01"= "AVG_of_DEWPOINT01";
      this."AVG_of_DPT01"= "AVG_of_DPT01";
      this."AVG_of_DPT02"= "AVG_of_DPT02";
      this."AVG_of_FEEDAMP"= "AVG_of_FEEDAMP";
      this."AVG_of_FEEDHZ"= "AVG_of_FEEDHZ";
      this."AVG_of_FLOW"= "AVG_of_FLOW";
      this."AVG_of_HZ01"= "AVG_of_HZ01";
      this."AVG_of_MILLAMP"= "AVG_of_MILLAMP";
      this."AVG_of_MILLHZ"= "AVG_of_MILLHZ";
      this."AVG_of_O2FT_MAIN"= "AVG_of_O2FT_MAIN";
      this."AVG_of_PRESSURE01"= "AVG_of_PRESSURE01";
      this."AVG_of_SEPAMP"= "AVG_of_SEPAMP";
      this."AVG_of_SEPHZ"= "AVG_of_SEPHZ";
      this."AVG_of_SPEED"= "AVG_of_SPEED";
      this."AVG_of_TEMP3"= "AVG_of_TEMP3";
      this."AVG_of_TEMP4"= "AVG_of_TEMP4";
      this."AVG_of_TEMP5"= "AVG_of_TEMP5";
      this."AVG_of_TEMP6"= "AVG_of_TEMP6";
      this."INSP_ITEM"= "INSP_ITEM";
      this."LSL"= "LSL";
      this."USL"= "USL";
      this."VALUE"= "VALUE";
 
      _ZT5K8HFT9737OKKI23QHL6U1.scoreRecord();
      _93GQLBVUVAYYGWZUXHWT8P1FX();
      post_93GQLBVUVAYYGWZUXHWT8P1FX();
 
      "EM_CLASSIFICATION"= this."EM_CLASSIFICATION";
      "EM_EVENTPROBABILITY"= this."EM_EVENTPROBABILITY";
      "EM_PROBABILITY"= this."EM_PROBABILITY";
      "I_DEF"= this."I_DEF";
      "P_DEFMIS_H"= this."P_DEFMIS_H";
      "P_DEFOK"= this."P_DEFOK";
   end;
 
endpackage;
